name: Main

on: workflow_dispatch

jobs:
  Build:
    name: ${{ matrix.name }}
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: iOS
            os: macos-26
            buildArgs: "ios -nosign"
            assetType: ASTC
            artifactName: iOSBuild
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
          - name: iOS (Simulator)
            os: macos-26
            buildArgs: "ios -simulator -nosign"
            assetType: ASTC
            artifactName: iOSSimulatorBuild
            artifactPath: "export/release/ios/build/Release-iphonesimulator/*.ipa"
    secrets:
      SE_KEYSTORE_FILE: ${{ secrets.SE_KEYSTORE_FILE }}
      SE_KEYSTORE_INFO_FILE: ${{ secrets.SE_KEYSTORE_INFO_FILE }}
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      assetType: ${{ matrix.assetType }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}
